In [2]:
input = '''.....613...................................439............498.........................438......617....343.............942...................
.......*............790...........269..735..*........................../679..............*444.*.........*.......147...*.............441.....
....539......422.......*......662*........*..691..........*124.15..675.................=.......404...872............237......930.....+......
........334.............861.........%....479..........424.......+.@.......402.......314...905................833........*293................
..........#.......................906.................*...............950.....................712...437.........*142.359........551.14......
....509.....=...........890...................&........9................./..847.154..568............@...102................280...*..........
.....*..950.67.............-......161.......530....=...................=............*...../..............@.......................426........
614...............................*.............59.591.....259*.......342...427..........29../.........-....................946.............
.......896........808..............6.............*.............35............./......538.....572....510...677*380...........=...............
.......*.............*534..814................879...............................615/....*............................90.........580...413...
.......810..........................................714.260..498..........386..........877......754........793...943.*............/.....*...
.....................845..#..483........55...643.......*......&.....421..+.....+...527.....938............*.......*...993...............706.
....339*..370..........-.540.@.....337..........*........39........*........404......&.......*...483...308.....567................../.......
..........*......994..............*......855..356.768.....*.....114...@195..................976....-...............496.61...610...369.200...
..........15........*...@890...447.........*.........*.303......................821..251*....................8........*....+................
...962.............260...................@..716....893..............304............*.....537.........805.....#..........................388.
............201*........................281.............471........*...../.....=....959...............%..238....180..641@...................
....278.........132..........65...&.........*920.......*.......831..97..828.....533......#368............../.......*......66-...............
.....*................*......*..627......343..........111.....*.....................................*.100$........693..........780..........
...974........474..537.759.101.......366....................183...............461*178..850.......644.........57.............................
..........67$.@.........................*...879..................54.100..355.................794.............=.....................826.530..
494*549...............670...=194.....173............329=....*14....*........*....811*303....*....891..541........975........................
........................*................403.............591................667............630....*.....$.667*....#...*......819.........19.
572...@.......%.......271..........910.........578.551..........818.534...........................217.........809.....262.....+.............
.....105.......748..............%........637...*...*........515....*...................119............*143..@.....258.......................
.20........115........714....525...491....*..768...647.....*...................433..../............583.......404..#..............268........
.......650..*.....%......%............*.311............275.283.306..=659.....................499........@................652.176............
..100.....#.193.637..........828...806.............725*........*..............................@......418........370.......@........86&..977.
......350................229..$.............................%...724.....#.981*582..$...............................*.38.....38.503......$...
.......#..380...........*.............311........%..........968......647..........33..................634*13......72./...%...*..*...........
............*.203*52.......+........./...........295.....................888..........277...938..662.........3.........619.320...766........
....149...883..............817...........163............959..........8.....*.811%............*......&...354..+.....392......................
....................727........789......*...............@...............739.........537....326.............*......*.......&925.........938..
..383..505.166......-.........*.......565......491........136.....693..........870.%...........#...........654..&..313.................*....
.........=..$..801....962.....787..........181......186.../..........*103........+............826....599.......289.....311.768..........986.
.292.414..........*......*................*..................214.....................439.@130...........+...52........*.....*.....989*......
.........221......149....405...@...........393..........714.....&.......652............*............607....*.........412....682.......982...
.........*......................491.......................*..............-......906..909.......885.....%.747......19........................
......567.........193........1..................925.........78......117.....797*................@............208............................
.............943..*.....571...*.....919.487............/....+.........*.......................................*......433.922.......795......
....66......*....92..........367.......*....883.625.....479....852@.............277.635............860.......940..21....*....995.....&......
.........206............595%...................*............./.......................*......691.......*..........*..........*...............
.....766.............&................=...........*...649-.241...56..@724..713..836.863.......=....676...+..824.506......247..$132..........
.....................278..........917..864.....219...............+............%.*......................973.........................744......
.........912...............%......*................979....-953...................733.............&................................*.........
.........@........$........995....905......552...................391.........40=.......388.......141...................731*640.....511......
123..662...989.672............................*........611......+.....%910.............*....5......................584......................
...*...*../...........................306.....289.*....*.............................673.....*........970..51....@....*...............#.....
...916.23.......14..828........908.................181.227......26....190.....723..*.......877...513...@...*..977......319..867/...997..76..
..........158........=............$..............................%............#...605....................264.......569.....................1
.....453..*............................815.430*........946..840.........................456.........152................23...................
216.....*.389...........930............*.......211.......-...*.....635..472*185.................................@444...*.....783...966......
...*...72.................*..........527...+...............636.......*.............746....575.....5...276.821........568.+......*...-.......
..765...........991........686..142*......588......@...........366....395.............*..*...............................983...266..........
.................+..................383.............330..&......%...............337.853.337........927.@703.&513......................855...
...652................=../..@.............431....48......512...............541....%.................+.............-...835/.......%......*...
.....*..205.....510.92..901.778............*......./............588.........#..........@....................968.603........820...75....844..
...560............/........................597...................&.......#............698..........427........*...../249....................
..............817..........50..........208..................149..........169........................*......835..............522.............
.....-......................*............*.....470......%..*.......151.................731.......395..979.........200.........#.......$.....
..242.........698........763............531.....*....252...533.....*.........64.........*...233.........*............*262.............498...
........994.....*...............620.639......575................934..606.99....*....770.72.#......@.............................-...........
.......*.........658..355.........#...*............*...*597..............*...645......*........292........-..354...@.......409...515........
........453..594.......#..............571..=552.193...8.............820...69.........877....%..........846.....*...525.446....*........*386.
....&...........#..................................................*....-.................652.................500............361....290.....
...833..................652.....410..924*72..........*.../104.....231.223....@...%....775................375................................
.................470...........*..................663.......................179.10....&.........256..770*............243.........354........
...*5.............*............962......-....................../.....529...................../.....*.........39.255./.......73......&.......
...............253..766....$.............659........$497..241.656....&....630................262.212...154.......*............*.............
...................*....755...................375...........*................@...........................*.....936...159.......786...981....
...................78....................426.....*39....885..835....432..............439.................335............@...................
.......*574.785............................................*................736......*.....860....395...........381...........@..114...825..
....557........@.............187.....640......514.36*.....834.........630...@....*..194......#....-......*......*....164....440.%.....*.....
...................744.908....*........*......*......185......................165........635..........464.354..104.................996......
.........................*.805..604..375...326........................*.................../....970.....................*....................
....751.....776.......661.......*.................777*........434..952.662....2......................$.923...........99.463.........&.514...
....*........*.....55..........414..............................*..............$......&522........378............+............*....89..*....
.331.......403..94..................547.551..............300...600........=......452.......976.+...............213.........815.757..........
.....209-......*...760...............@...*.............................963........+..........*.906.......785...........................+....
958...........319....@.....+.334..........640.................................798.........611......678.....*..630.......389............426..
.........../............961..*..................608..472...........45...........*...................*....390.............*..................
.....597..191......&861.......279.689.............=....*.972*..........560......900.............548..97.......240...51....2....411.......233
......*.......379.................*......+...........770.....989...955...&.214#.........*588.......*.............%..$.......................
....982.&.......................82....850...450......................*...............755.....799....539.....298.........993........788......
.........901....382.......569...............&........428............281.....=599.........98.../....................789.@......956.=....450..
.................*..497/..*...664....*...............%.........610................/944.....*....778......713*375.....*.................*....
.......@......637........443.../...905............................*883.......389...........563......................388...$.....*559....386.
........241.......*597.........................876..............$........731*.....192.483..............#958...%..*......828..100............
...89&.........994.........*228...............#...........18...413..............1....*...........*..........157...453.......................
..........573...........198............447........488.672../.#......&383.........%.....589........511..................46...................
.....*449......$...228*................+.............*........662.........%.............*....321........34%....838&...*.....................
..592.......659...............=...........................................188..248....836......*....................141..%......344.........
............................564....481..............-..........................................861............%...........93.....$...$.936..
..........618.287......490$.......-............*..304.........662.........@....196...@...72*.........918.339.999.-.................28.......
.............*..............................556.......812.272.....235@.510...#.....51.......804...........#.......209......323=.............
.../471..474.................446.......*........855....*....#..............265..................588.24.......522............................
............*........86..755..+........664........*.....311........793.361.....685.......859..../...@..158......=...667#...........871......
...........529.........&.*.........................624........578....*...................*..................334..........843................
....32#........12..818...406......888.........555........678...*...................@....796.%........159.......-.......$.......@142..289....
..........797..@...*..........246....*..........*.............473............485..683.......526.......*................987...........*......
...272....-.......763...........*...............546....203......................%..................560.....294........................921...
......+...............439...144..909....221...............*245.............847....971..........812............*.............................
...........66....+.........*.........20......337.....591.......*.226.&.....*.......-..+113........./........321..756...518....*.............
......325......166..........848................*.267*........857..*..34.....471.............579+.851...322........#...*........125..........
.........*..........157......................77..................567....646...........................*......783....634.5....@..............
.598.497.275.......&......908=............................................$.......172*324...$263.....207......&.........@...340...160....80.
....*..................#........484..833.998....*.....#.......945.135.......108..................104........................................
..............908....645..264*..........*....581.332...519.......*.........*...........811..................214&..$............57...........
....%543.......@..............807..768.......................23............578.........&.....545...................988........*.........#...
...........547..........&.818........*................669....*........395.........88........*.....964*.....................230..105....471..
......................231.&.........645....*982..398...@.....442..........................311.........466....168..788..474......-...........
..233......638.254......................824..........%...........676.....413......818.............................*.......*.................
..............*.........672.137..............866...862...376........*.........933*............455.................158....682..180*333.......
........454$...........*.......................*........#.............................../18.....*.....677...664.........................%867
..............318....107...........*793.....361...............................*................372.......*.....*509......765.203....737.....
.................%........*.216.831....................509.....392............508...........&...........780.........219.....*......&....*635
334............&........862................945.....162*.........*.......529.......164.......627.381*........591........*83...........155....
.......278...476....363....../.........785.%................431...........*..........*529...........194......*..............982*91..........
.......*..................994..480.....*......*.......236...*........825.450......&.......&..797*.......634.249.......................626...
408.699........*527............*....900....145.880...*......833......*...........456....914......432...*...............391..537........*....
.........................836..955.....................126............557.............................870...38..........*.....*.......388....
.................+275.......*..................=................/............526..................................-....66....587............
..........................400....&............933.......*.....535........455*.....&...209.699........90....*10..207...............*.67......
..............757................719.-............*..-...38.....................22.....*..+...254.....$.736..................201.80.+.......
.....86.584............+..*..........531........335.949.......500...........544.....22.11....*......%.........774*434...337...........331...
.183...*............553....691..131..........................*.................*..............186..591..=171............................*...
...*..........645........*.........*.......365............654......*........843..649.............................673.....867........#.218...
....533..206..*...528=...618........891.41*......................988.596........$......%......391..506..672...../...........*103..926.......
............$.49..............*.....................445................@..../......&..678...................61..............................
..63.............998.......927...295..600....303..........352..............358...464......234.......-.......*....517.......-778....32..641..
....*693............*..............*...*...+.../..70......@...417......*.......$.........*..........417...940.....@....................*....
.................529...561.......706...894.740.......117=....+.......251....642...&763..183..................................$..............
544.651.......+........*....951..................438............505..................................309......800..........534..............
...*...........864.....930....*...36*.......418....*...............*................703...............*.........%..431................=.....
...........463................73.....476............942...55.....127..........................560..959................*.............255.....
......%...*.......176..969#...............@35...............*........-.........242...............=.........147.......914....191.............
....71....686................*.................260.........62.423...823..............-.....................*...................=.186........
.................521..447....940...123........*.................+..........62....855..452...............455.......264....9..........*165....
.......$608..675*.....*.../.......*............72......../...........*484....*....=................................*......*.....%...........
...................302..476.......64.....................159......815......445..........965........................558...824....281......98.'''

TODO:
1. Extract surrounding rows to calculate neighbors
2. group numbers together and search for a neighbor in the surrounding bounding box
3. if symbol is located, move that number to a list
4. sum up list

In [3]:
import numpy as np
import re

In [4]:
rows = input.split('\n')

def get_surrounding_rows(idx):
    current_row = rows[idx]

    if 0<idx<len(rows)-1:
        previous_row = rows[idx-1]
        next_row = rows[idx+1]
        return (previous_row,current_row,next_row)
    elif idx == 0:
        next_row = rows[idx+1]
        return (current_row,next_row)
    else:
        previous_row = rows[idx-1]
        return (previous_row,current_row)

In [5]:
len(rows)

140

In [6]:
def get_number_indexes(row):
    digits = re.finditer(r'\d',row)
    digit_idxs = [digit.start(0) for digit in digits]
    return digit_idxs

def get_symbol_indexes(row):
    symbols = re.finditer(r'[\!\@\#\$\%\^\&\*\-\+\=\/]',row.replace('.','p'))
    symbol_idxs = [symbol.start(0) for symbol in symbols]
    return symbol_idxs

In [7]:
def group_numbers(arr):
    groups = []
    sub_group = []
    for idx,num in enumerate(arr):
        sub_group.append(num)
        if idx != len(arr)-1:
            if arr[idx+1]-arr[idx]>1:
                groups.append(sub_group)
                sub_group=[]
        else:
            groups.append(sub_group)
    return groups

In [8]:
import random

In [9]:
part_numbers = []
total=0
for row_number in range(len(rows)):
    subset_rows = get_surrounding_rows(row_number)

    if row_number == 0:
        subset_numbers = get_number_indexes(subset_rows[0])
    else:
        subset_numbers = get_number_indexes(subset_rows[1])
 
    subset_numbers_grouped= group_numbers(subset_numbers)
    for num in subset_numbers_grouped:
        if num[0] == 0:
            idx_start = num[0]
        else:
            idx_start = num[0]-1
        idx_end = num[-1]+2
        for subset_row in subset_rows:
            #search for symbols in each row based on index range
            symbols = get_symbol_indexes(subset_row[idx_start:idx_end])
            if symbols:
                try:
                    part_num = int(subset_rows[0][num[0]:num[-1]+1])
                    part_numbers.append(part_num)
                    total+=part_num
                except:
                    part_num = int(subset_rows[1][num[0]:num[-1]+1])                   
                    part_numbers.append(part_num)
                    total+=part_num

In [10]:
total

527144

Part 2
TODO:
1. Locate Numbers
2. Locate Gears
3. Locate numbers that are adjacent to gears and record gear location along with number
4. If more than one number shares a gear location, add numbers as tuple to list
5.

In [11]:
def get_gear_indexes(row):
    symbols = re.finditer(r'[\*]',row.replace('.','p'))
    symbol_idxs = [symbol.start(0) for symbol in symbols]
    return symbol_idxs

In [12]:
import pandas as pd

In [141]:
df = pd.DataFrame(columns = ['number','gear_col','gear_row'])
gear_array = []
total=0
row_tracker = 0
for row_number in range(len(rows)):
    subset_rows = get_surrounding_rows(row_number)

    if row_number == 0:
        subset_numbers = get_number_indexes(subset_rows[0])
    else:
        subset_numbers = get_number_indexes(subset_rows[1])
 
    subset_numbers_grouped= group_numbers(subset_numbers)
    
    for num in subset_numbers_grouped:
        if num[0] == 0:
            idx_start = num[0]
        else:
            idx_start = num[0]-1
        idx_end = num[-1]+2
        for idx,subset_row in enumerate(subset_rows):
            #search for symbols in each row based on index range
            symbols = get_gear_indexes(subset_row[idx_start:idx_end])
            if symbols:
                try:
                    part_num = int(subset_rows[0][num[0]:num[-1]+1])
                    df = df._append({'number':part_num, 'gear_col':idx_start+symbols[0], 'gear_row':row_tracker+idx}, ignore_index=True)
                except:
                    part_num = int(subset_rows[1][num[0]:num[-1]+1])                   
                    df = df._append({'number':part_num, 'gear_col':idx_start+symbols[0], 'gear_row':row_tracker-1+idx}, ignore_index=True)

    row_tracker+=1

In [109]:
rows[0:5]

['.....613...................................439............498.........................438......617....343.............942...................',
 '.......*............790...........269..735..*........................../679..............*444.*.........*.......147...*.............441.....',
 '....539......422.......*......662*........*..691..........*124.15..675.................=.......404...872............237......930.....+......',
 '........334.............861.........%....479..........424.......+.@.......402.......314...905................833........*293................',
 '..........#.......................906.................*...............950.....................712...437.........*142.359........551.14......']

In [142]:
df.sort_values(by=['gear_row', 'gear_col']).head(20)

   number gear_col gear_row
0     613        7        1
10    539        7        1
1     439       44        1
12    691       44        1
2     438       89        1
9     444       89        1
3     617       94        1
14    404       94        1
4     343      104        1
15    872      104        1
5     942      118        1
16    237      118        1
6     790       23        2
17    861       23        2
7     269       33        2
11    662       33        2
8     735       42        2
18    479       42        2
13    124       58        2
21    293      120        3

In [104]:
rows[0:2]

['.....613...................................439............498.........................438......617....343.............942...................',
 '.......*............790...........269..735..*........................../679..............*444.*.........*.......147...*.............441.....']

In [143]:
df['combined'] = df['gear_col'].astype(str)+df['gear_row'].astype(str)

In [144]:
df= df.sort_values(by='combined').reset_index(drop=True)

In [145]:
df.combined.value_counts()

combined
347      4
39130    2
5272     2
5517     2
5511     2
        ..
2429     1
25126    1
15119    1
26115    1
10018    1
Name: count, Length: 365, dtype: int64

In [146]:
df_uniq = df[df.duplicated(subset=['combined'], keep=False)]

In [147]:
df_uniq.head(10)

   number gear_col gear_row combined
1     427      100       58    10058
2     395      100       58    10058
3     678      100       80    10080
4      97      100       80    10080
5     466      101      109   101109
6     964      101      109   101109
7      15       10       13     1013
8     370       10       13     1013
9     686       10      135    10135
10    463       10      135    10135

In [135]:
#df_uniq['other_num'] = df_uniq.number.iloc[1]

C:\Users\alexf\AppData\Local\Temp\ipykernel_13160\1886824595.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_uniq['other_num'] = df_uniq.number.iloc[1]

In [149]:
even_list = [x for x in range(df_uniq.shape[0]) if x%2==0]
odd_list = [x for x in range(df_uniq.shape[0]) if x%2!=0]

In [150]:
df_even= df_uniq.iloc[even_list]
df_odd = df_uniq.iloc[odd_list]

df_all = df_even.merge(df_odd,on=['gear_row','gear_col'])

In [151]:
df_all.head(10)

  number_x gear_col gear_row combined_x number_y combined_y
0      427      100       58      10058      395      10058
1      678      100       80      10080       97      10080
2      466      101      109     101109      964     101109
3       15       10       13       1013      370       1013
4      686       10      135      10135      463      10135
5      207      102      104     102104      322     102104
6      309      102      133     102133      959     102133
7      143      102       24      10224      583      10224
8      676      102       41      10241      860      10241
9      159      102       99      10299      560      10299

In [152]:
df_all['total'] = df_all.number_x*df_all.number_y

In [153]:
df_all

    number_x gear_col gear_row combined_x number_y combined_y   total
0        427      100       58      10058      395      10058  168665
1        678      100       80      10080       97      10080   65766
2        466      101      109     101109      964     101109  449224
3         15       10       13       1013      370       1013    5550
4        686       10      135      10135      463      10135  317618
..       ...      ...      ...        ...      ...        ...     ...
317      432       96      118      96118      797      96118  344304
318      217       98       22       9822      891       9822  193347
319      194       99      116      99116      381      99116   73914
320      256       99       67       9967      212       9967   54272
321      539       99       82       9982      548       9982  295372

[322 rows x 7 columns]

In [154]:
df_all.total.sum()

81463996