In [3]:
import pandas as pd
import numpy as np

In [24]:
3333452986+455063168

3788516154

In [34]:
seeds = '4088478806 114805397 289354458 164506173 1415635989 166087295 1652880954 340945548 3561206012 483360452 35205517 252097746 1117825174 279314434 3227452369 145640027 2160384960 149488635 2637152665 236791935'

seed_soil = '''3333452986 2926455387 455063168
3222292973 1807198589 111160013
4073195028 1120843626 221772268
3215232741 2255546991 7060232
1658311530 2727928910 32644400
2680271553 1918358602 337188389
1690955930 3973557555 28589896
2081345351 4046183137 248784159
2374165196 3613106716 306106357
1553535599 2504868379 49003335
4018850546 3919213073 54344482
2050713919 2287201502 30631432
3183342019 1775307867 31890722
3975551599 2553871714 43298947
1120843626 1342615894 432691973
2330129510 4002147451 44035686
1719545826 2628348978 99579932
1819125758 3381518555 231588161
1627133213 2597170661 31178317
3017459942 2760573310 165882077
3788516154 2317832934 187035445
1602538934 2262607223 24594279'''

soil_fert ='''2037529808 755544791 28492175
786265521 51055407 490038659
4209265112 3740304131 26706989
1490754905 2631438697 34586718
1525341623 2263058012 73974507
1774661286 1921164897 262868522
3007460847 4099468601 72419286
3538443051 3849232192 250236409
1276304180 541094066 214450725
3913003454 3767011120 59428684
1599316130 2497793999 133644698
3079880133 3189897565 426082572
716780020 784036966 69485501
1732960828 0 41700458
2066021983 41700458 9354949
0 853522467 536962937
3972432138 2920584245 236832974
536962937 2337032519 100792490
4272174908 3826439804 22792388
3788679460 3615980137 124323994
2135345922 1446730958 474433939
637755427 2184033419 79024593
2884381438 4171887887 123079409
2075376932 2437825009 59968990
4235972101 2884381438 36202807
2609779861 1390485404 56245554
3505962705 3157417219 32480346'''

fert_water ='''2573961911 2642757339 200829754
422488483 458127884 156893128
2774791665 2843587093 21928567
579381611 0 138939
1694098304 2191562282 184724096
3947192080 3245704277 276559964
972559115 1385376838 44883044
3491468609 3875486597 235886348
1207641311 1359799603 25577235
2301984556 4185647450 96253759
3943275635 3001826942 3916445
901810658 387379427 70748457
285678041 1226326727 103026012
0 775143786 192216167
3304976053 3522264241 95407569
2086394179 1904419031 20334668
2797747442 1694098304 113068417
2398238315 1924753699 175723596
4223752044 2376286378 71215252
192216167 1132864853 93461874
392041619 1329352739 30446864
736305758 967359953 44331476
3740421044 2865515660 136311282
388704053 771806220 3337566
2796720232 4111372945 1027210
3727354957 4281901209 13066087
1017442159 197180275 190199152
1878822400 4112400155 6703986
3400383622 2100477295 91084987
780637234 1011691429 121173424
1885526386 3674618804 200867793
2910815859 3617671810 56946994
2967762853 1807166721 97252310
3065015163 3005743387 239960890
1233218546 138939 197041336
2106728847 2447501630 195255709
579520550 615021012 156785208
3876732326 4119104141 66543309'''

water_light = '''1713604757 2608139445 8097487
416889953 2083343492 58961768
1343227622 1417788674 170490633
2121243443 2549534549 51843959
3366419885 3580448237 174948163
2173087402 0 443149530
3030450490 4139087067 155880229
3186330719 3883823748 51661818
1513718255 1282808215 134980459
1075515973 1815631843 267711649
967716956 443149530 107799017
3237992537 3755396400 128427348
3825109759 3262058246 318389991
879862906 954959732 80165960
6760937 1035125692 247682523
2953403197 3185010953 77047293
960028866 2541846459 7688090
4143499750 3033543407 151467546
2749801696 3935485566 203601501
1648698714 1750725800 64906043
254443460 1588279307 162446493
475851721 550948547 404011185
3541368048 2749801696 283741711
1721702244 2142305260 399541199
0 2601378508 6760937'''

light_temp ='''72585995 0 6987206
3613700480 3337307014 262222114
3107305066 2641039316 68521519
1346057837 1130104209 332811266
1789578875 2709560835 110508022
1678869103 3335693412 1613602
4221249401 2413595122 73717895
1283830508 2273268756 62227329
2654986608 3645211688 211881713
1900086897 3599529128 45682560
866613618 2487313017 153726299
1945769457 1462915475 224589729
2170359186 2335496085 78099037
1020339917 866613618 263490591
3175826585 3857093401 437873895
1680482705 3226597242 109096170
2866868321 1687505204 240436745
3875922594 1927941949 345326807
2248458223 2820068857 406528385
0 6987206 72585995'''

temp_humid = '''688557414 35571309 205276783
1344556852 4212560627 61250968
3617960922 3570339727 35153299
1798596843 4122755682 89804945
968601622 2840504203 289938389
3674269922 3395595703 19024769
2596309702 1911252584 80861179
2438263727 2065549417 13406592
1405807820 1518463561 392789023
617995054 866387965 70562360
1258540011 2078956009 86016841
3395085595 2301904832 149439673
4212818712 3130442592 82148584
1888401788 968601622 549861939
3005925897 2451344505 389159698
3544525268 1992113763 73435654
929405506 858843146 7544819
3868591817 3605493026 188507640
3653114221 4273811595 21155701
893834197 0 35571309
2588602301 3387888302 7707401
2677170881 3794000666 328755016
4057099457 3414620472 155719255
0 240848092 617995054
3693294691 3212591176 175297126
2451670319 2164972850 136931982'''

humid_loc ='''3586928302 2065932610 149219519
709155282 323064563 19167863
1359021687 3937987878 39697029
4009761511 2966667063 138486244
300370292 619673957 122108798
1230327417 992326977 128694270
1524755905 3624589590 105592616
3736147821 2637585432 174385627
1068077767 3730182206 162249650
3120252652 1674438017 80200651
434861301 1581164273 93273744
3489613286 225749547 97315016
2210476726 741782755 111642249
1630348521 1811987842 123678973
1456067890 2488658901 68688015
2890604013 917374342 74952635
2638888586 853425004 63949338
528135045 2557346916 80238516
2440002559 2215152129 198886027
608373561 3105153307 100781721
3910533448 342232426 99228063
4148247755 3892431856 45556022
2702837924 4107201207 187766089
1754027494 1121021247 298601872
2322118975 1948049026 117883584
889864299 441460489 178213468
3200453303 3559871086 36387444
225749547 2414038156 74620745
422479090 1935666815 12382211
728323145 1419623119 161541154
1398718716 1754638668 57349174
2052629366 3977684907 129516300
4193803777 3458707567 101163519
2182145666 3596258530 28331060
2965556648 2811971059 154696004
3236840747 3205935028 252772539'''

In [35]:
maps = [seed_soil,soil_fert,fert_water,water_light,light_temp,temp_humid,humid_loc]

In [122]:
maps_rev = [humid_loc,temp_humid,light_temp,water_light,fert_water,soil_fert,seed_soil]

In [33]:
def create_maps(src_map):
    maps = src_map.split('\n')
    map_list = []
    for item in maps:
        vals = [int(val) for val in item.split(' ')]
        map_list.append({'source_start':vals[1],'source_end':vals[1]+vals[2],
                            'dest_start':vals[0],'dest_end':vals[0]+vals[2]})
    return pd.DataFrame(map_list)

In [53]:
temp_humid_df = create_maps(temp_humid)

In [40]:
seeds = [int(x) for x in seeds.split(' ')]

In [42]:
def get_dest_value(source_val, df):
    for idx, row in df.iterrows():
        if row.source_start<=source_val<=row.source_end:
            range_diff = source_val -row.source_start
            dest = row.dest_start+range_diff
            return dest

    return source_val

In [47]:
loc_values = []
for seed in seeds:
    start_seed = True
    for map in maps:
        df = create_maps(map)
        if start_seed:
            new_src_val = get_dest_value(seed,df)
            start_seed = False
        else:
            new_src_val = get_dest_value(new_src_val,df)
    print(seed,new_src_val)

4088478806 3014755458
114805397 1690141612
289354458 925969269
164506173 2452872251
1415635989 2253918459
166087295 2454453373
1652880954 4027561917
340945548 977560359
3561206012 3399734119
483360452 2023666033
35205517 3258643866
252097746 4008609769
1117825174 382895070
279314434 915929245
3227452369 2638545227
145640027 3730151367
2160384960 4171407620
149488635 3733999975
2637152665 641984578
236791935 3993303958

In [130]:
temp_humid_df

    source_start  source_end  dest_start    dest_end
0       35571309   240848092   688557414   893834197
1     4212560627  4273811595  1344556852  1405807820
2     3570339727  3605493026  3617960922  3653114221
3     4122755682  4212560627  1798596843  1888401788
4     2840504203  3130442592   968601622  1258540011
5     3395595703  3414620472  3674269922  3693294691
6     1911252584  1992113763  2596309702  2677170881
7     2065549417  2078956009  2438263727  2451670319
8     1518463561  1911252584  1405807820  1798596843
9      866387965   936950325   617995054   688557414
10    2078956009  2164972850  1258540011  1344556852
11    2301904832  2451344505  3395085595  3544525268
12    3130442592  3212591176  4212818712  4294967296
13     968601622  1518463561  1888401788  2438263727
14    2451344505  2840504203  3005925897  3395085595
15    1992113763  2065549417  3544525268  3617960922
16     858843146   866387965   929405506   936950325
17    3605493026  3794000666  3868591817  4057099457
18    4273811595  4294967296  3653114221  3674269922
19             0    35571309   893834197   929405506
20    3387888302  3395595703  2588602301  2596309702
21    3794000666  4122755682  2677170881  3005925897
22    3414620472  3570339727  4057099457  4212818712
23     240848092   858843146           0   617995054
24    3212591176  3387888302  3693294691  3868591817
25    2164972850  2301904832  2451670319  2588602301

In [141]:
start_map = True
for map in maps_rev:
    print('new map')
    df = create_maps(map)
    if start_map:
        source = df[df.dest_start == df.dest_start.min()]['source_start'].values[0]
        start_map = False
    else:
        for idx, row in df.iterrows():
            if row.dest_start<=source<=row.dest_end:
                print(idx)
                print(f'dest:{source}')
                print(f'source_start: {row.source_start}')
                if row.source_start+source-row.dest_start<row.source_end:
                    source = row.source_start+source-row.dest_start
                print(f'source:{source}')
                break

new map
new map
13
dest:2414038156
source_start: 968601622
source:1494237990
new map
3
dest:1494237990
source_start: 1130104209
source:1278284362
new map
9
dest:1278284362
source_start: 1815631843
source:2018400232
new map
30
dest:2018400232
source_start: 3674618804
source:3807492650
new map
19
dest:3807492650
source_start: 3615980137
source:3634793327
new map
0
dest:3634793327
source_start: 2926455387
source:3227795728

In [142]:
source

3227795728

In [143]:
seeds = [source]

In [144]:
loc_values = []
for seed in seeds:
    start_seed = True
    for map in maps:
        df = create_maps(map)
        if start_seed:
            new_src_val = get_dest_value(seed,df)
            start_seed = False
        else:
            new_src_val = get_dest_value(new_src_val,df)
        print(seed,new_src_val)

3227795728 3634793327
3227795728 3807492650
3227795728 2018400232
3227795728 1278284362
3227795728 1494237990
3227795728 2414038156
3227795728 2638888586

In [124]:
df.loc[df.dest_start == df.dest_start.min()]

    source_start  source_end  dest_start    dest_end
14    1342615894  1775307867  1120843626  1553535599

In [157]:
from functools import reduce

seeds, *mappings = open('data.txt').read().split('\n\n')
seeds = [int(x) for x in seeds.split()[1:]]

def lookup(inputs, mapping):
    for start, length in inputs:
        while length > 0:
            for m in mapping.split('\n')[1:]:
                dst, src, len = [int(x) for x in m.split()]
                delta = start - src
                if delta in range(len):
                    len = min(len - delta, length)
                    yield (dst + delta, len)
                    start += len
                    length -= len
                    break
            else: yield (start, length); break

print(*[min(reduce(lookup, mappings, s))[0] for s in [
    zip(seeds, [1] * len(seeds)),
    zip(seeds[0::2], seeds[1::2])]])

382895070 17729182

In [156]:
mappings

['seed-to-soil map:\n3333452986 2926455387 455063168\n3222292973 1807198589 111160013\n4073195028 1120843626 221772268\n3215232741 2255546991 7060232\n1658311530 2727928910 32644400\n2680271553 1918358602 337188389\n1690955930 3973557555 28589896\n2081345351 4046183137 248784159\n2374165196 3613106716 306106357\n1553535599 2504868379 49003335\n4018850546 3919213073 54344482\n2050713919 2287201502 30631432\n3183342019 1775307867 31890722\n3975551599 2553871714 43298947\n1120843626 1342615894 432691973\n2330129510 4002147451 44035686\n1719545826 2628348978 99579932\n1819125758 3381518555 231588161\n1627133213 2597170661 31178317\n3017459942 2760573310 165882077\n3788516154 2317832934 187035445\n1602538934 2262607223 24594279',
 'soil-to-fertilizer map:\n2037529808 755544791 28492175\n786265521 51055407 490038659\n4209265112 3740304131 26706989\n1490754905 2631438697 34586718\n1525341623 2263058012 73974507\n1774661286 1921164897 262868522\n3007460847 4099468601 72419286\n3538443051 3849232192 250236409\n1276304180 541094066 214450725\n3913003454 3767011120 59428684\n1599316130 2497793999 133644698\n3079880133 3189897565 426082572\n716780020 784036966 69485501\n1732960828 0 41700458\n2066021983 41700458 9354949\n0 853522467 536962937\n3972432138 2920584245 236832974\n536962937 2337032519 100792490\n4272174908 3826439804 22792388\n3788679460 3615980137 124323994\n2135345922 1446730958 474433939\n637755427 2184033419 79024593\n2884381438 4171887887 123079409\n2075376932 2437825009 59968990\n4235972101 2884381438 36202807\n2609779861 1390485404 56245554\n3505962705 3157417219 32480346',
 'fertilizer-to-water map:\n2573961911 2642757339 200829754\n422488483 458127884 156893128\n2774791665 2843587093 21928567\n579381611 0 138939\n1694098304 2191562282 184724096\n3947192080 3245704277 276559964\n972559115 1385376838 44883044\n3491468609 3875486597 235886348\n1207641311 1359799603 25577235\n2301984556 4185647450 96253759\n3943275635 3001826942 3916445\n901810658 387379427 70748457\n285678041 1226326727 103026012\n0 775143786 192216167\n3304976053 3522264241 95407569\n2086394179 1904419031 20334668\n2797747442 1694098304 113068417\n2398238315 1924753699 175723596\n4223752044 2376286378 71215252\n192216167 1132864853 93461874\n392041619 1329352739 30446864\n736305758 967359953 44331476\n3740421044 2865515660 136311282\n388704053 771806220 3337566\n2796720232 4111372945 1027210\n3727354957 4281901209 13066087\n1017442159 197180275 190199152\n1878822400 4112400155 6703986\n3400383622 2100477295 91084987\n780637234 1011691429 121173424\n1885526386 3674618804 200867793\n2910815859 3617671810 56946994\n2967762853 1807166721 97252310\n3065015163 3005743387 239960890\n1233218546 138939 197041336\n2106728847 2447501630 195255709\n579520550 615021012 156785208\n3876732326 4119104141 66543309',
 'water-to-light map:\n1713604757 2608139445 8097487\n416889953 2083343492 58961768\n1343227622 1417788674 170490633\n2121243443 2549534549 51843959\n3366419885 3580448237 174948163\n2173087402 0 443149530\n3030450490 4139087067 155880229\n3186330719 3883823748 51661818\n1513718255 1282808215 134980459\n1075515973 1815631843 267711649\n967716956 443149530 107799017\n3237992537 3755396400 128427348\n3825109759 3262058246 318389991\n879862906 954959732 80165960\n6760937 1035125692 247682523\n2953403197 3185010953 77047293\n960028866 2541846459 7688090\n4143499750 3033543407 151467546\n2749801696 3935485566 203601501\n1648698714 1750725800 64906043\n254443460 1588279307 162446493\n475851721 550948547 404011185\n3541368048 2749801696 283741711\n1721702244 2142305260 399541199\n0 2601378508 6760937',
 'light-to-temperature map:\n72585995 0 6987206\n3613700480 3337307014 262222114\n3107305066 2641039316 68521519\n1346057837 1130104209 332811266\n1789578875 2709560835 110508022\n1678869103 3335693412 1613602\n4221249401 2413595122 73717895\n1283830508 2273268756 62227329\n2654986608 3645211688 211881713\n1900086897 3599529128 45682560\n866613618 2487313017 153726299\n1945769457 1462915475 224589729\n2170359186 2335496085 78099037\n1020339917 866613618 263490591\n3175826585 3857093401 437873895\n1680482705 3226597242 109096170\n2866868321 1687505204 240436745\n3875922594 1927941949 345326807\n2248458223 2820068857 406528385\n0 6987206 72585995',
 'temperature-to-humidity map:\n688557414 35571309 205276783\n1344556852 4212560627 61250968\n3617960922 3570339727 35153299\n1798596843 4122755682 89804945\n968601622 2840504203 289938389\n3674269922 3395595703 19024769\n2596309702 1911252584 80861179\n2438263727 2065549417 13406592\n1405807820 1518463561 392789023\n617995054 866387965 70562360\n1258540011 2078956009 86016841\n3395085595 2301904832 149439673\n4212818712 3130442592 82148584\n1888401788 968601622 549861939\n3005925897 2451344505 389159698\n3544525268 1992113763 73435654\n929405506 858843146 7544819\n3868591817 3605493026 188507640\n3653114221 4273811595 21155701\n893834197 0 35571309\n2588602301 3387888302 7707401\n2677170881 3794000666 328755016\n4057099457 3414620472 155719255\n0 240848092 617995054\n3693294691 3212591176 175297126\n2451670319 2164972850 136931982',
 'humidity-to-location map:\n3586928302 2065932610 149219519\n709155282 323064563 19167863\n1359021687 3937987878 39697029\n4009761511 2966667063 138486244\n300370292 619673957 122108798\n1230327417 992326977 128694270\n1524755905 3624589590 105592616\n3736147821 2637585432 174385627\n1068077767 3730182206 162249650\n3120252652 1674438017 80200651\n434861301 1581164273 93273744\n3489613286 225749547 97315016\n2210476726 741782755 111642249\n1630348521 1811987842 123678973\n1456067890 2488658901 68688015\n2890604013 917374342 74952635\n2638888586 853425004 63949338\n528135045 2557346916 80238516\n2440002559 2215152129 198886027\n608373561 3105153307 100781721\n3910533448 342232426 99228063\n4148247755 3892431856 45556022\n2702837924 4107201207 187766089\n1754027494 1121021247 298601872\n2322118975 1948049026 117883584\n889864299 441460489 178213468\n3200453303 3559871086 36387444\n225749547 2414038156 74620745\n422479090 1935666815 12382211\n728323145 1419623119 161541154\n1398718716 1754638668 57349174\n2052629366 3977684907 129516300\n4193803777 3458707567 101163519\n2182145666 3596258530 28331060\n2965556648 2811971059 154696004\n3236840747 3205935028 252772539']